export default {
    baniya: {
      agarwal: [
        "goyal",
        "bansal",
        "kucchal",
        "Kansal",
        "Jindal",
        "Mittal",
        "Tayal",
        "Bindal",
        "Singhal",
        "Garg",
        "Gupta",
      ],
      maheswari: [
        "Ajmera",
        "Asava",
        "Attal",
        "Agiwal",
        "Aagsuad",
        "Baldua",
        "Baaldi",
        "Boob",
        "Bangad",
        "Bihani",
        "Bidada",
        "Baheti",
        "Bajaj",
        "Birla",
        "Bang",
        "Bhandari",
        "Bhattad",
        "Bhutada",
      ],
      khandelwal: [],
      mahawar: [],
    },
  };

