export default {
  Baniya: {
    Agarwal: [
      "Airan",
      "Bansal",
      "Bindal",
      "Bhandal",
      "Dharan",
      "Garg",
      "Goyal",
      "Goyan",
      "Jindal",
      "Kansal",
      "Kuchhal",
      "Madhukul",
      "Mangal",
      "Mittal",
      "Nangal",
      "Singhal",
      "Tayal",
      "Tingal",
    ],
    Maheswari: [
      "Ajmera",
      "Asava",
      "Attal",
      "Agiwal",
      "Aagsuad",
      "Baldua",
      "Baaldi",
      "Boob",
      "Bangad",
      "Bihani",
      "Bidada",
      "Baheti",
      "Bajaj",
      "Birla",
      "Bang",
      "Bhandari",
      "Bhattad",
      "Bhutada",
    ],
    Khandelwal: [],
    Mahawar: [],
  },
};
